apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lmgq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0017-tenant/tkrw-pr712-0075-0017-app/devfile-sample-lmgq@sha256:2989993a6ed8d6626327d59871cefdcc4fc60c837df270201660a71a21c4a02f
        name: my-nodejs
        resources: {}
status: {}
